### ISSUE TITLE
Add Full-Text search for various Java resources

### ISSUE THREAD

**Issue by marchof** [marchof/java-almanac#212]
An aggregates search should be added to quickly find various Java resources.

## TODO

- [ ] Add Index for javaalmanac.io content
- [ ] Add Index for API diffs
- [ ] Add index for Java versions < Java 13
- [ ] Count hits by tag
- [ ] Add filtering
- [ ] Add search box to javaalmanac.io page headers
- [ ] Set focus on search field
